/*
 * Softomate Person API
 *
 * This is a API for Softomate testwork
 *
 * OpenAPI spec version: 1.0.0
 * Contact: imail.for.iwork@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using IO.Swagger.Attributes;
using IO.Swagger.Models;
using Softomate.context;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class UsersApiController : Controller
    {
        private IContext db;
        
        public UsersApiController(IContext context)
        {
            db = context;
        }

        /// <summary>
        /// get all persons
        /// </summary>
        /// <remarks>get all person in system</remarks>
        /// <response code="200">all persons taken</response>
        /// <response code="400">Bad request</response>
        /// <response code="404">Not found</response>
        /// <response code="500">Internal server error</response>
        [HttpGet]
        [Route("/api/v1/softomate/person")]
        [ValidateModelState]
        [SwaggerOperation("GetAllPersons")]
        [SwaggerResponse(200, typeof(List<Person>), "all persons taken")]
        [SwaggerResponse(400, typeof(ErrorMessage), "Bad request")]
        [SwaggerResponse(404, typeof(ErrorMessage), "Not found")]
        [SwaggerResponse(500, typeof(ErrorMessage), "Internal server error")]
        public virtual IActionResult GetAllPersons()
        { 
            return new ObjectResult(db.GetPersons());
        }
        
        /// <summary>
        /// create Person
        /// </summary>
        /// <remarks>create new Person</remarks>
        /// <param name="person"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad request</response>
        /// <response code="404">Not found</response>
        /// <response code="409">Conflict</response>
        /// <response code="500">Internal server error</response>
        [HttpPost]
        [Route("/api/v1/softomate/person")]
        [ValidateModelState]
        [SwaggerOperation("CreateNewPerson")]
        public virtual void CreateNewPerson([FromBody]Person person)
        { 
             db.CreatePerson(person);
        }

        /// <summary>
        /// get person by id
        /// </summary>
        /// <remarks>get Person by id if exists or null otherwise</remarks>
        /// <param name="id"></param>
        /// <response code="200">ok</response>
        /// <response code="400">Bad request</response>
        /// <response code="404">Not found</response>
        /// <response code="500">Internal server error</response>
        [HttpGet]
        [Route("/api/v1/softomate/person/{id}")]
        [ValidateModelState]
        [SwaggerOperation("GetPersonById")]
        [SwaggerResponse(200, typeof(Person), "ok")]
        [SwaggerResponse(400, typeof(ErrorMessage), "Bad request")]
        [SwaggerResponse(404, typeof(ErrorMessage), "Not found")]
        [SwaggerResponse(500, typeof(ErrorMessage), "Internal server error")]
        public virtual IActionResult GetPersonById([FromRoute]string id)
        { 
            return  new ObjectResult(db.GetPerson(id));
        }
        
        /// <summary>
        /// delete an Person
        /// </summary>
        /// <remarks>delete an Person</remarks>
        /// <param name="id"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad request</response>
        /// <response code="404">Not found</response>
        /// <response code="409">Conflict</response>
        /// <response code="500">Internal server error</response>
        [HttpDelete]
        [Route("/api/v1/softomate/person/{id}")]
        [ValidateModelState]
        [SwaggerOperation("DeletePerson")]
        public virtual void DeletePerson([FromRoute]string id)
        {
            db.DeletePerson(id);
        }

        /// <summary>
        /// update an Person record
        /// </summary>
        /// <remarks>update an Person record</remarks>
        /// <param name="person"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad request</response>
        /// <response code="404">Not found</response>
        /// <response code="409">Conflict</response>
        /// <response code="500">Internal server error</response>
        [HttpPut]
        [Route("/api/v1/softomate/person")]
        [ValidateModelState]
        [SwaggerOperation("UpdatePerson")]
        public virtual void UpdatePerson([FromBody]Person person)
        {
            db.UpdatePerson(person);
        }
    }
}
